// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Trim possible surrounding quotes from .env values
const SUPABASE_URL = rawUrl ? rawUrl.replace(/^\"|\"$/g, '') : rawUrl;
const SUPABASE_PUBLISHABLE_KEY = rawKey ? rawKey.replace(/^\"|\"$/g, '') : rawKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Provide clear runtime warning to help debugging env issues
  // eslint-disable-next-line no-console
  console.warn('Supabase client initialized without URL or key. Check VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env');
}

// Export debug info (safe to log in dev; don't expose service key in production)
export const SUPABASE_DEBUG = {
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
};